<?php

namespace CodersLabBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{

public function findAllContacts() {
    $people = $this->getEntityManager()->createQuery(
        'SELECT people FROM CodersLabBundle:Person people ORDER BY people.surname ASC'
    )->getResult();

    return $people;
}

}
