<?php

namespace CodersLabBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneNumberRepository extends EntityRepository
{
}
